config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do 
    namespace :v1 do 
     resources :articles, only: [:index, :create, :destroy, :update]
     resources :questions, only: [:index, :create, :destroy, :update]
    end 
  end 
  root to: 'home#index'
  post 'home/import' => 'home#import', as: :import_questions
  get 'home/view_data' => 'home#view_data'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mapping.rb
class Mapping < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  require 'csv'
  require 'activerecord-import/base'
  require 'activerecord-import/active_record/adapters/postgresql_adapter'

  def self.my_import(file)
    questions = []
    mappings = []
    roles = []
    
    CSV.foreach(file.path, headers: true) do |row|
      questions << Question.new({ pri: row['Pri'], question: row['Question'], teaming_stage: row['Teaming Stages'],
      	                        appears_day: row['Appears (Day)'], frequency: row['Frequency'], question_type: row['Type'],
      	                        role: row['Role'], required: row['Required?'], conditions: row['Conditions'], mapping: row['Mapping'] })
      mappings << Mapping.new({ name: row['Mapping']})
      roles << Role.new(name: row['Role'])
    end
    Question.import questions, recursive: true
    Mapping.import mappings.uniq {|m| m.name}, recursive: true
    Role.import roles.uniq {|m| m.name}, recursive:true
   end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
	def index
	  render json: Question.all
	end
	
	def create
	  question = Question.create(question_params)
	  render json: question
	end
	
	def destroy
	  Question.destroy(params[:id])
	end
	
	def update
	  question = Question.find(params[:id])
	  question.update_attributes(question_params)
	  render json: question
	end
	
	private
	
	def question_params
	  params.require(:question).permit(:id, :pri, :question, :teaming_stage, :appears_day, :frequency, :question_type, :role, :required, :conditions, :mapping)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def import
    	if params[:file].blank?
    		redirect_to root_path, notice: "Select CSV file first and Import"
    	else
		    Question.my_import(params[:file])
		    redirect_to home_view_data_path, notice: "Successfully Imported Data!!!"
		end
	end

	def view_data
	end

  end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<div class='container'>
<center>
<%= flash[:notice] %>

  <h4 class='import_csv'>Import CSV Data!</h4>
  <%= form_tag import_questions_path, multipart: true do %>
    <%= file_field_tag :file,  class: 'csv_file btn btn-default' %>
    <br />
    <%= submit_tag "Import CSV", class: 'btn btn-info' %>	
  <% end %>
  
 <br>
  <p class='data_view'><%= link_to "Click here to view Imported Data", home_view_data_path %> </p>
  </center>
</div>

<style type="text/css">
	input{
		width: 500px !important;
	}
	.csv_file{
		margin-right: 25px;
	}
	.import_csv{
		margin-right: 320px;
	}
	.data_view{
		margin-right: 265px;
	}
</style>

app/views/home/view_data.html.erb
<%= link_to "Click Here to Import CSV Data", root_path %>
<%= flash[:notice] %>
<%= react_component 'Main' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactRorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">
    <center><h1>ROR React CRUD</h1></center>
    <hr>
    <%= yield %>
  </body>
</html>

<style type="text/css">
  input{width: 130px;}
</style>